### ISSUE TITLE
App BirrasTeam

### ISSUE THREAD

**Issue by Luis-Rodes** [Luis-Rodes/BirrasTeam.github.io#1]
Buenos dias @pedroprieto  quiero ver si entre unas cosas y otras me da tiempo a poder realizar esta App para el equipo de padel que tenemos los amigos.
La duda es saber si le puedes ir dando un vistazo cuando me enganche en algo.
Por ejemplo estoy intentando crear los apartados pero no me funciona el router salvo solo el inicio, es decir le doy a sobre nosotros pero no me muestra nada, y en inicio me aparece el index, si pudieras ver en que me estoy equivocando, pero sin prisa, ya te digo que esto es algo que queria hacer y voy a ver si puedo poco a poco.
Si tienes mucho lio no te preocupes de verdad que no hay problema.
Un saludo pedro.

**Comment by pedroprieto** [comment]
Buenas,
- Esto lo tienes que descomentar:
  https://github.com/Luis-Rodes/BirrasTeam.github.io/blob/ad0dcfa78aa3daca900a418ad6a0c9ff864f5f21/src/App.vue#L13
- Esto está mal: tienes que indicar las rutas bien
  https://github.com/Luis-Rodes/BirrasTeam.github.io/blob/ad0dcfa78aa3daca900a418ad6a0c9ff864f5f21/src/components/Inicio.vue#L31-L32
  ```html
  <a class="nav-link active"><router-link :to="'/PlantillaJugadores'" >Plantilla jugadores</router-link></a> 
  <a class="nav-link "><router-link :to="'/SobreNosotros'" >Sobre Nosotros</router-link></a> 
  ```
- Y aquí, indicar bien las rutas:
  https://github.com/Luis-Rodes/BirrasTeam.github.io/blob/ad0dcfa78aa3daca900a418ad6a0c9ff864f5f21/src/main.js#L14-L15
  ```js
    {path: '/SobreNosotros' , component: SobreNosotros},
    {path: '/PlantillaJugadores' , component: PlantillaJugadores}
  ```

Saludos,

Pedro Prieto

**Comment by Luis-Rodes** [comment]
Buenas @pedroprieto  ya he realizado algunos cambios, he tenido que meter todo el nav en el header de App porque me repetía el menú en inicio, me mostraba dos menús. También he quitado la prop del msg, ya que no conseguía que me mostrara la prop. Tengo mucho contenido comentado ya que estoy haciendo pruebas y hasta que no lo tenga mas o menos claro hay mucho código que esta puesto de referencia para mí. No se si va bien encaminada lo que quiero hacer, pero cuando te aburras dale un vistazo a ver como la ves. Por cierto se que comentaste algo sobre las pages en github, creo, bueno no lo he hecho bien porque no me aparece la pagina, me da error de consola al cargar el main.js, si pudieras darle un vistazo te o agradecería, pero vamos como te digo es un proyecto que quiero ver si me va saliendo sin prisa. Hablamos.

**Comment by pedroprieto** [comment]
Ok. Para el despliegue: https://vitejs.dev/guide/static-deploy

**Comment by Luis-Rodes** [comment]
Buenas @pedroprieto le he dado un vistazo al enlace y creo que era lo que ya nos dijiste y he puesto en el readme, pero me salen cosas que no logro entender.
Primero cuando le doy a npm run build, me ha creado las carpetas pero en la consola de aparecen errores:
<pre>
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///F:/BirrasTeam/BirrasTeam/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:67432:27)
    at onRollupWarning (file:///F:/BirrasTeam/BirrasTeam/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:67460:9)
    at onwarn (file:///F:/BirrasTeam/BirrasTeam/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:67164:13)
    at file:///F:/BirrasTeam/BirrasTeam/node_modules/rollup/dist/es/shared/node-entry.js:18335:13
    at Object.logger [as onLog] (file:///F:/BirrasTeam/BirrasTeam/node_modules/rollup/dist/es/shared/node-entry.js:19983:9)
    at ModuleLoader.handleInvalidResolvedId (file:///F:/BirrasTeam/BirrasTeam/node_modules/rollup/dist/es/shared/node-entry.js:18925:26)
    at file:///F:/BirrasTeam/BirrasTeam/node_modules/rollup/dist/es/shared/node-entry.js:18883:26
</pre>
despues cuando le doy al npm run preview, me sale el puerto 4173 y solo me aparece la parte del menú, pero si hago el npm run dev y me manda al puerto 5173, si puedo ver lo que de momento estoy creando.
por otro lado en la pagina de github https://luis-rodes.github.io/BirrasTeam.github.io/ no me aparece nada, la pagina en blanco con el codigo html del index y en la consola me da el error del main.js 
<pre>
Se bloqueó la carga de un módulo de “https://luis-rodes.github.io/src/main.js” debido a un tipo MIME no permitido (“text/html”).
</pre>
He eliminado todo el código comentado para verlo mas limpio, se que mi idea principal no es esa, pero no me veo capacitado para crear una API y que los datos los coja de la api en lugar de meterlo a mano en html, pero ya te digo no me veo capacitado por lo que he estado investigando de crear mi propia API.
Si tienes algún enlace donde pueda ver o tratar de entender mejor como crear la api, para que los datos aparezcan como hicimos con la API de github mándamelo y trato de ver algo.Ya me vas contando y vamos hablando Pedro.
Gracias de nuevo y perdona las molestias.

**Comment by pedroprieto** [comment]
Buenas, @Luis-Rodes 

Perdona por haber tardado en contestar.

He creado un vídeo para publicar proyectos de VueJS en GitHub Pages. En él hablo del problema que tienes:
https://youtu.be/8oF68bUibZw

Espero que te sirva. Un saludo!!

**Comment by Luis-Rodes** [comment]
Buenas @pedroprieto  no te preocupes, ya te comente que es un proyecto a largo plazo y que quiero mejorarlo poco a poco y eso lleva darte mucho follón. Además voy liado con el proyecto y demás cosas. Le pego un vistazo y cualquier cosa te voy comentando.
Gracias por todo y perdona las molestias. Saludos Luis Rodes.

**Comment by Luis-Rodes** [comment]
Buenas de nuevo @pedroprieto he realizado todo y  me sigue dando el error cuando hace el build la aplicacion, en localhost si se ve bien y funciona todo pero a la hora de compilar el build me da error.
Al principio me daba error el componente de PlantillaJugadores.vue, lo he borrado y actualizado pero me da el mismo erro y en los ficheros que me manda el error son demasiado para mi y no veo donde darle
Tambien he probado a cambiar el nombre al componenete a PlantillaDeJugadores y me da error tambien, pienso que tiene que ser algo del codigo pero no veo nada.

**Comment by pedroprieto** [comment]
Buenas,

El fichero se llama `PlantillaDeJugadores.vue`, pero la ruta no lleva `De`:
https://github.com/Luis-Rodes/BirrasTeam/blob/2180d0f247ef20784bb6ce42128d115fb44eefb4/src/main.js#L15

**Comment by Luis-Rodes** [comment]
Buenas @pedroprieto  le cambio la ruta pero es por lo que te comente, con plantillajugadores daba error y la elimine y cambie por otra para ver si funcionaba, se me paso cambiar esa ruta,  creo que no subí el cambio pero sigue dándome el error al hacer el build 
<pre>
transforming...
✓ 13 modules transformed.
x Build failed in 103ms
error during build:
Error: [vite]: Rollup failed to resolve import "..." from "/home/runner/work/BirrasTeam/BirrasTeam/src/components/PlantillaDeJugadores.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///home/runner/work/BirrasTeam/BirrasTeam/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:67432:27)
    at onRollupWarning (file:///home/runner/work/BirrasTeam/BirrasTeam/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:67460:9)
    at onwarn (file:///home/runner/work/BirrasTeam/BirrasTeam/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:67164:13)
    at file:///home/runner/work/BirrasTeam/BirrasTeam/node_modules/rollup/dist/es/shared/node-entry.js:18335:13
    at Object.logger [as onLog] (file:///home/runner/work/BirrasTeam/BirrasTeam/node_modules/rollup/dist/es/shared/node-entry.js:19983:9)
    at ModuleLoader.handleInvalidResolvedId (file:///home/runner/work/BirrasTeam/BirrasTeam/node_modules/rollup/dist/es/shared/node-entry.js:18925:26)
    at file:///home/runner/work/BirrasTeam/BirrasTeam/node_modules/rollup/dist/es/shared/node-entry.js:18883:26
Error: Process completed with exit code 1.
</pre>

**Comment by pedroprieto** [comment]
Buenas,

El fallo está en las rutas `...` que pones en los atributos `src` de las imágenes. Quítalas o pon rutas válidas:
https://github.com/Luis-Rodes/BirrasTeam/blob/5d3335f7714d06110b3fb5fb7ed31fe7810c5c35/src/components/PlantillaDeJugadores.vue#L13
https://github.com/Luis-Rodes/BirrasTeam/blob/5d3335f7714d06110b3fb5fb7ed31fe7810c5c35/src/components/PlantillaDeJugadores.vue#L22
https://github.com/Luis-Rodes/BirrasTeam/blob/5d3335f7714d06110b3fb5fb7ed31fe7810c5c35/src/components/PlantillaDeJugadores.vue#L31
https://github.com/Luis-Rodes/BirrasTeam/blob/5d3335f7714d06110b3fb5fb7ed31fe7810c5c35/src/components/PlantillaDeJugadores.vue#L40

**Comment by Luis-Rodes** [comment]
Buenas @pedroprieto Vale perdona que sea tan corto pedro, ahora viendo el mensaje si veo lo del fallo del import de los " ... " pero creía que siempre venia de la pagina.
Vale gracias sigo con esto poco a poco a ver que tal y como te comente, lo próximo es intentar hacer una api para que los jugadores pongan sus datos y hacer un for en la pagina y ver que tal.
Te cuento cosas por aquí si me quedo enganchado otra vez.
Saludos Pedro.
